### ISSUE TITLE
backtrace shown when incorrect resource name is passed to -g

### ISSUE THREAD

**Issue by gergnz** [stevenjack/cfndsl#338]
If you run with an unknown resource type when generating, cfndsl spits out a backtrace. What should happen is we capture this and suggest to the user that maybe the resource type is incorrect.

```bash
$ cfndsl -g RDS_DBInstance,sitecoredb
/Users/gregc/.rvm/gems/ruby-2.3.3/gems/cfndsl-0.15.2/lib/cfnlego/resource.rb:21:in `properties': undefined method `[]' for nil:NilClass (NoMethodError)
	from (erb):8:in `block in render'
	from (erb):4:in `each'
	from (erb):4:in `render'
	from /Users/gregc/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from /Users/gregc/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/erb.rb:864:in `result'
	from /Users/gregc/.rvm/gems/ruby-2.3.3/gems/cfndsl-0.15.2/lib/cfnlego/cloudformation.rb:16:in `render'
	from /Users/gregc/.rvm/gems/ruby-2.3.3/gems/cfndsl-0.15.2/lib/cfnlego.rb:36:in `run'
	from /Users/gregc/.rvm/gems/ruby-2.3.3/gems/cfndsl-0.15.2/bin/cfndsl:99:in `<top (required)>'
	from /Users/gregc/.rvm/gems/ruby-2.3.3/bin/cfndsl:22:in `load'
	from /Users/gregc/.rvm/gems/ruby-2.3.3/bin/cfndsl:22:in `<main>'
	from /Users/gregc/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/gregc/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by kornypoet** [comment]
We used to do something similar to this at one point. The code that handled  it was pretty messy, and it tended to obfuscate other real errors.
